### ISSUE TITLE
Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"

### ISSUE THREAD

**Issue by johnsonsamuel** [typegoose/mongodb-memory-server#754] opened 2023-03-16 16:05 UTC
Instance failed to start because a library is missing or cannot be opened: "libcrypto.so.1.1"

## Versions

- NodeJS: 16.19.1
- mongodb-memory-server-*: 8.12.0

**Comment by hasezoey** [comment] 2023-03-16 16:11
Duplicate of #732

**Closed as completed by hasezoey** 2023-03-16 16:11 UTC
Labels: bug, duplicate
